<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Italy', 'continent_id' => '6', 'code' => 'IT'],
            ['name' => 'United States', 'continent_id' => '3', 'code' => 'US'],
            ['name' => 'Algeria', 'continent_id' => '1', 'code' => 'DZ'],
            ['name' => 'Wallis and Futuna', 'continent_id' => '4', 'code' => 'WF'],
            ['name' => 'Angola', 'continent_id' => '1', 'code' => 'AO'],
            ['name' => 'Benin', 'continent_id' => '1', 'code' => 'BJ'],
            ['name' => 'Botswana', 'continent_id' => '1', 'code' => 'BW'],
            ['name' => 'Burkina Faso', 'continent_id' => '1', 'code' => 'BF'],
            ['name' => 'Burundi', 'continent_id' => '1', 'code' => 'BI'],
            ['name' => 'Cameroon', 'continent_id' => '1', 'code' => 'CM'],
            ['name' => 'Cape Verde', 'continent_id' => '1', 'code' => 'CV'],
            ['name' => 'Central African Republic', 'continent_id' => '1', 'code' => 'CF'],
            ['name' => 'Chad', 'continent_id' => '1', 'code' => 'TD'],
            ['name' => 'Comoros', 'continent_id' => '1', 'code' => 'KM'],
            ['name' => 'Congo - Brazzaville', 'continent_id' => '1', 'code' => 'CG'],
            ['name' => 'Congo - Kinshasa', 'continent_id' => '1', 'code' => 'CD'],
            ['name' => 'Cote d\'Ivoire', 'continent_id' => '1', 'code' => 'CI'],
            ['name' => 'Djibouti', 'continent_id' => '1', 'code' => 'DJ'],
            ['name' => 'Egypt', 'continent_id' => '1', 'code' => 'EG'],
            ['name' => 'Equatorial Guinea', 'continent_id' => '1', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'continent_id' => '1', 'code' => 'ER'],
            ['name' => 'Ethiopia', 'continent_id' => '1', 'code' => 'ET'],
            ['name' => 'Gabon', 'continent_id' => '1', 'code' => 'GA'],
            ['name' => 'Gambia', 'continent_id' => '1', 'code' => 'GM'],
            ['name' => 'Ghana', 'continent_id' => '1', 'code' => 'GH'],
            ['name' => 'Guinea', 'continent_id' => '1', 'code' => 'GN'],
            ['name' => 'Guinea Bissau', 'continent_id' => '1', 'code' => 'GW'],
            ['name' => 'Kenya', 'continent_id' => '1', 'code' => 'KE'],
            ['name' => 'Lesotho', 'continent_id' => '1', 'code' => 'LS'],
            ['name' => 'Liberia', 'continent_id' => '1', 'code' => 'LR'],
            ['name' => 'Libya', 'continent_id' => '1', 'code' => 'LY'],
            ['name' => 'Madagascar', 'continent_id' => '1', 'code' => 'MG'],
            ['name' => 'Malawi', 'continent_id' => '1', 'code' => 'MW'],
            ['name' => 'Mali', 'continent_id' => '1', 'code' => 'ML'],
            ['name' => 'Mauritania', 'continent_id' => '1', 'code' => 'MR'],
            ['name' => 'Mauritius', 'continent_id' => '1', 'code' => 'MU'],
            ['name' => 'Mayotte', 'continent_id' => '1', 'code' => 'YT'],
            ['name' => 'Morocco', 'continent_id' => '1', 'code' => 'MA'],
            ['name' => 'Mozambique', 'continent_id' => '1', 'code' => 'MZ'],
            ['name' => 'Namibia', 'continent_id' => '1', 'code' => 'NA'],
            ['name' => 'Niger', 'continent_id' => '1', 'code' => 'NE'],
            ['name' => 'Vanuatu', 'continent_id' => '4', 'code' => 'VU'],
            ['name' => 'Rwanda', 'continent_id' => '1', 'code' => 'RW'],
            ['name' => 'Reunion', 'continent_id' => '1', 'code' => 'RE'],
            ['name' => 'Saint Helena', 'continent_id' => '1', 'code' => 'SH'],
            ['name' => 'Senegal', 'continent_id' => '1', 'code' => 'SN'],
            ['name' => 'Seychelles', 'continent_id' => '1', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'continent_id' => '1', 'code' => 'SL'],
            ['name' => 'Somalia', 'continent_id' => '1', 'code' => 'SO'],
            ['name' => 'South Africa', 'continent_id' => '1', 'code' => 'ZA'],
            ['name' => 'Sudan', 'continent_id' => '1', 'code' => 'SD'],
            ['name' => 'Swaziland', 'continent_id' => '1', 'code' => 'SZ'],
            ['name' => 'Sao Tome and Príncipe', 'continent_id' => '1', 'code' => 'ST'],
            ['name' => 'Tanzania', 'continent_id' => '1', 'code' => 'TZ'],
            ['name' => 'Togo', 'continent_id' => '1', 'code' => 'TG'],
            ['name' => 'Tunisia', 'continent_id' => '1', 'code' => 'TN'],
            ['name' => 'Uganda', 'continent_id' => '1', 'code' => 'UG'],
            ['name' => 'U.S. Minor Outlying Islands', 'continent_id' => '4', 'code' => 'UM'],
            ['name' => 'Tuvalu', 'continent_id' => '4', 'code' => 'TV'],
            ['name' => 'Western Sahara', 'continent_id' => '1', 'code' => 'EH'],
            ['name' => 'Zambia', 'continent_id' => '1', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'continent_id' => '1', 'code' => 'ZW'],
            ['name' => 'Anguilla', 'continent_id' => '3', 'code' => 'AI'],
            ['name' => 'Antigua and Barbuda', 'continent_id' => '3', 'code' => 'AG'],
            ['name' => 'Argentina', 'continent_id' => '7', 'code' => 'AR'],
            ['name' => 'Aruba', 'continent_id' => '7', 'code' => 'AW'],
            ['name' => 'Bahamas', 'continent_id' => '3', 'code' => 'BS'],
            ['name' => 'Barbados', 'continent_id' => '7', 'code' => 'BB'],
            ['name' => 'Belize', 'continent_id' => '3', 'code' => 'BZ'],
            ['name' => 'Bermuda', 'continent_id' => '3', 'code' => 'BM'],
            ['name' => 'Bolivia', 'continent_id' => '7', 'code' => 'BO'],
            ['name' => 'Brazil', 'continent_id' => '7', 'code' => 'BR'],
            ['name' => 'British Virgin Islands', 'continent_id' => '3', 'code' => 'VG'],
            ['name' => 'Canada', 'continent_id' => '3', 'code' => 'CA'],
            ['name' => 'Cayman Islands', 'continent_id' => '3', 'code' => 'KY'],
            ['name' => 'Chile', 'continent_id' => '7', 'code' => 'CL'],
            ['name' => 'Colombia', 'continent_id' => '7', 'code' => 'CO'],
            ['name' => 'Costa Rica', 'continent_id' => '3', 'code' => 'CR'],
            ['name' => 'Cuba', 'continent_id' => '3', 'code' => 'CU'],
            ['name' => 'Dominica', 'continent_id' => '3', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'continent_id' => '3', 'code' => 'DO'],
            ['name' => 'Ecuador', 'continent_id' => '7', 'code' => 'EC'],
            ['name' => 'El Salvador', 'continent_id' => '3', 'code' => 'SV'],
            ['name' => 'Falkland Islands', 'continent_id' => '7', 'code' => 'FK'],
            ['name' => 'French Guiana', 'continent_id' => '7', 'code' => 'GF'],
            ['name' => 'Greenland', 'continent_id' => '3', 'code' => 'GL'],
            ['name' => 'Grenada', 'continent_id' => '3', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'continent_id' => '3', 'code' => 'GP'],
            ['name' => 'Guatemala', 'continent_id' => '3', 'code' => 'GT'],
            ['name' => 'Guyana', 'continent_id' => '7', 'code' => 'GY'],
            ['name' => 'Haiti', 'continent_id' => '3', 'code' => 'HT'],
            ['name' => 'Honduras', 'continent_id' => '3', 'code' => 'HN'],
            ['name' => 'Jamaica', 'continent_id' => '3', 'code' => 'JM'],
            ['name' => 'Martinique', 'continent_id' => '3', 'code' => 'MQ'],
            ['name' => 'Mexico', 'continent_id' => '7', 'code' => 'MX'],
            ['name' => 'Montserrat', 'continent_id' => '3', 'code' => 'MS'],
            ['name' => 'Netherlands Antilles', 'continent_id' => '7', 'code' => 'AN'],
            ['name' => 'Nicaragua', 'continent_id' => '3', 'code' => 'NI'],
            ['name' => 'Panama', 'continent_id' => '3', 'code' => 'PA'],
            ['name' => 'Paraguay', 'continent_id' => '7', 'code' => 'PY'],
            ['name' => 'Peru', 'continent_id' => '7', 'code' => 'PE'],
            ['name' => 'Puerto Rico', 'continent_id' => '3', 'code' => 'PR'],
            ['name' => 'Saint Barthelemy', 'continent_id' => '3', 'code' => 'BL'],
            ['name' => 'Saint Kitts and Nevis', 'continent_id' => '3', 'code' => 'KL'],
            ['name' => 'Saint Lucia', 'continent_id' => '3', 'code' => 'LC'],
            ['name' => 'Saint Martin', 'continent_id' => '3', 'code' => 'MF'],
            ['name' => 'Saint Pierre and Miquelon', 'continent_id' => '3', 'code' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'continent_id' => '3', 'code' => 'VC'],
            ['name' => 'Suriname', 'continent_id' => '7', 'code' => 'SR'],
            ['name' => 'Trinidad and Tobago', 'continent_id' => '7', 'code' => 'TT'],
            ['name' => 'Turks and Caicos Islands', 'continent_id' => '3', 'code' => 'TC'],
            ['name' => 'U.S. Virgin Islands', 'continent_id' => '3', 'code' => 'VI'],
            ['name' => 'Tonga', 'continent_id' => '4', 'code' => 'TO'],
            ['name' => 'Uruguay', 'continent_id' => '7', 'code' => 'UY'],
            ['name' => 'Venezuela', 'continent_id' => '7', 'code' => 'VE'],
            ['name' => 'Tokelau', 'continent_id' => '4', 'code' => 'TK'],
            ['name' => 'Afghanistan', 'continent_id' => '5', 'code' => 'AF'],
            ['name' => 'Armenia', 'continent_id' => '5', 'code' => 'AM'],
            ['name' => 'Azerbaijan', 'continent_id' => '5', 'code' => 'AZ'],
            ['name' => 'Bahrain', 'continent_id' => '5', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'continent_id' => '5', 'code' => 'BD'],
            ['name' => 'Bhutan', 'continent_id' => '5', 'code' => 'BT'],
            ['name' => 'Brunei', 'continent_id' => '5', 'code' => 'BN'],
            ['name' => 'Cambodia', 'continent_id' => '5', 'code' => 'KH'],
            ['name' => 'China', 'continent_id' => '5', 'code' => 'CN'],
            ['name' => 'Cyprus', 'continent_id' => '5', 'code' => 'CY'],
            ['name' => 'Georgia', 'continent_id' => '5', 'code' => 'GE'],
            ['name' => 'Hong Kong SAR China', 'continent_id' => '5', 'code' => 'HK'],
            ['name' => 'India', 'continent_id' => '5', 'code' => 'IN'],
            ['name' => 'Indonesia', 'continent_id' => '5', 'code' => 'ID'],
            ['name' => 'Iran', 'continent_id' => '5', 'code' => 'IR'],
            ['name' => 'Iraq', 'continent_id' => '5', 'code' => 'IQ'],
            ['name' => 'Israel', 'continent_id' => '5', 'code' => 'IL'],
            ['name' => 'Japan', 'continent_id' => '5', 'code' => 'JP'],
            ['name' => 'Jordan', 'continent_id' => '5', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'continent_id' => '5', 'code' => 'KZ'],
            ['name' => 'Kuwait', 'continent_id' => '5', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'continent_id' => '5', 'code' => 'KG'],
            ['name' => 'Laos', 'continent_id' => '5', 'code' => 'LA'],
            ['name' => 'Lebanon', 'continent_id' => '5', 'code' => 'LB'],
            ['name' => 'Macau SAR China', 'continent_id' => '5', 'code' => 'MO'],
            ['name' => 'Malaysia', 'continent_id' => '5', 'code' => 'MY'],
            ['name' => 'Maldives', 'continent_id' => '5', 'code' => 'MV'],
            ['name' => 'Mongolia', 'continent_id' => '5', 'code' => 'MN'],
            ['name' => 'Myanmar Burma', 'continent_id' => '5', 'code' => 'MM'],
            ['name' => 'Nepal', 'continent_id' => '5', 'code' => 'NP'],
            ['name' => 'Neutral Zone', 'continent_id' => '5', 'code' => 'NT'],
            ['name' => 'North Korea', 'continent_id' => '5', 'code' => 'KP'],
            ['name' => 'Oman', 'continent_id' => '5', 'code' => 'OM'],
            ['name' => 'Pakistan', 'continent_id' => '5', 'code' => 'PK'],
            ['name' => 'Palestinian Territories', 'continent_id' => '5', 'code' => 'PS'],
            ['name' => 'People s Democratic Republic of Yemen', 'continent_id' => '5', 'code' => 'YD'],
            ['name' => 'Philippines', 'continent_id' => '5', 'code' => 'PH'],
            ['name' => 'Qatar', 'continent_id' => '5', 'code' => 'QA'],
            ['name' => 'Saudi Arabia', 'continent_id' => '5', 'code' => 'SA'],
            ['name' => 'Singapore', 'continent_id' => '5', 'code' => 'SG'],
            ['name' => 'South Korea', 'continent_id' => '5', 'code' => 'KR'],
            ['name' => 'Sri Lanka', 'continent_id' => '5', 'code' => 'LK'],
            ['name' => 'Syria', 'continent_id' => '5', 'code' => 'SY'],
            ['name' => 'Taiwan', 'continent_id' => '5', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'continent_id' => '5', 'code' => 'TJ'],
            ['name' => 'Thailand', 'continent_id' => '5', 'code' => 'TH'],
            ['name' => 'Timor Leste', 'continent_id' => '5', 'code' => 'TL'],
            ['name' => 'Turkey', 'continent_id' => '5', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'continent_id' => '5', 'code' => 'TM'],
            ['name' => 'United Arab Emirates', 'continent_id' => '5', 'code' => 'AE'],
            ['name' => 'Uzbekistan', 'continent_id' => '5', 'code' => 'UZ'],
            ['name' => 'Vietnam', 'continent_id' => '5', 'code' => 'VN'],
            ['name' => 'Yemen', 'continent_id' => '5', 'code' => 'YE'],
            ['name' => 'Albania', 'continent_id' => '6', 'code' => 'AL'],
            ['name' => 'Andorra', 'continent_id' => '6', 'code' => 'AD'],
            ['name' => 'Austria', 'continent_id' => '6', 'code' => 'AT'],
            ['name' => 'Belarus', 'continent_id' => '6', 'code' => 'BY'],
            ['name' => 'Belgium', 'continent_id' => '6', 'code' => 'BE'],
            ['name' => 'Bosnia and Herzegovina', 'continent_id' => '6', 'code' => 'BA'],
            ['name' => 'Bulgaria', 'continent_id' => '6', 'code' => 'BG'],
            ['name' => 'Croatia', 'continent_id' => '6', 'code' => 'HR'],
            ['name' => 'South Georgia and the South Sandwich Isl', 'continent_id' => '4', 'code' => 'GS'],
            ['name' => 'Czech Republic', 'continent_id' => '6', 'code' => 'CZ'],
            ['name' => 'Denmark', 'continent_id' => '6', 'code' => 'DK'],
            ['name' => 'Estonia', 'continent_id' => '6', 'code' => 'EE'],
            ['name' => 'Faroe Islands', 'continent_id' => '6', 'code' => 'FO'],
            ['name' => 'Finland', 'continent_id' => '6', 'code' => 'FI'],
            ['name' => 'France', 'continent_id' => '6', 'code' => 'FR'],
            ['name' => 'Germany', 'continent_id' => '6', 'code' => 'DE'],
            ['name' => 'Gibraltar', 'continent_id' => '6', 'code' => 'GI'],
            ['name' => 'Greece', 'continent_id' => '6', 'code' => 'GR'],
            ['name' => 'Guernsey', 'continent_id' => '6', 'code' => 'GG'],
            ['name' => 'Hungary', 'continent_id' => '6', 'code' => 'HU'],
            ['name' => 'Iceland', 'continent_id' => '6', 'code' => 'IS'],
            ['name' => 'Ireland', 'continent_id' => '6', 'code' => 'IE'],
            ['name' => 'Isle of Man', 'continent_id' => '6', 'code' => 'IM'],
            ['name' => 'Jersey', 'continent_id' => '6', 'code' => 'JE'],
            ['name' => 'Latvia', 'continent_id' => '6', 'code' => 'LV'],
            ['name' => 'Liechtenstein', 'continent_id' => '6', 'code' => 'LI'],
            ['name' => 'Lithuania', 'continent_id' => '6', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'continent_id' => '6', 'code' => 'LU'],
            ['name' => 'Macedonia', 'continent_id' => '6', 'code' => 'MK'],
            ['name' => 'Malta', 'continent_id' => '6', 'code' => 'MT'],
            ['name' => 'Metropolitan France', 'continent_id' => '6', 'code' => 'FX'],
            ['name' => 'Moldova', 'continent_id' => '6', 'code' => 'MD'],
            ['name' => 'Monaco', 'continent_id' => '6', 'code' => 'MC'],
            ['name' => 'Montenegro', 'continent_id' => '6', 'code' => 'ME'],
            ['name' => 'Netherlands', 'continent_id' => '6', 'code' => 'NL'],
            ['name' => 'Norway', 'continent_id' => '6', 'code' => 'NO'],
            ['name' => 'Poland', 'continent_id' => '6', 'code' => 'PL'],
            ['name' => 'Portugal', 'continent_id' => '6', 'code' => 'PT'],
            ['name' => 'Romania', 'continent_id' => '6', 'code' => 'RO'],
            ['name' => 'Russia', 'continent_id' => '6', 'code' => 'RU'],
            ['name' => 'San Marino', 'continent_id' => '6', 'code' => 'SM'],
            ['name' => 'Serbia', 'continent_id' => '6', 'code' => 'RS'],
            ['name' => 'Serbia and Montenegro', 'continent_id' => '6', 'code' => 'CS'],
            ['name' => 'Slovakia', 'continent_id' => '6', 'code' => 'SK'],
            ['name' => 'Slovenia', 'continent_id' => '6', 'code' => 'SI'],
            ['name' => 'Spain', 'continent_id' => '6', 'code' => 'ES'],
            ['name' => 'Svalbard and Jan Mayen', 'continent_id' => '6', 'code' => 'SJ'],
            ['name' => 'Sweden', 'continent_id' => '6', 'code' => 'SE'],
            ['name' => 'Switzerland', 'continent_id' => '6', 'code' => 'CH'],
            ['name' => 'Ukraine', 'continent_id' => '6', 'code' => 'UA'],
            ['name' => 'Union of Soviet Socialist Republics', 'continent_id' => '6', 'code' => 'SU'],
            ['name' => 'United Kingdom', 'continent_id' => '6', 'code' => 'GB'],
            ['name' => 'Vatican City', 'continent_id' => '6', 'code' => 'VA'],
            ['name' => 'Aland Islands', 'continent_id' => '6', 'code' => 'AX'],
            ['name' => 'American Samoa', 'continent_id' => '4', 'code' => 'AS'],
            ['name' => 'Antarctica', 'continent_id' => '4', 'code' => 'AQ'],
            ['name' => 'Australia', 'continent_id' => '4', 'code' => 'AU'],
            ['name' => 'Bouvet Island', 'continent_id' => '4', 'code' => 'BV'],
            ['name' => 'British Indian Ocean Territory', 'continent_id' => '4', 'code' => 'IO'],
            ['name' => 'Christmas Island', 'continent_id' => '4', 'code' => 'CX'],
            ['name' => 'Cocos Keeling Islands', 'continent_id' => '4', 'code' => 'CC'],
            ['name' => 'Cook Islands', 'continent_id' => '4', 'code' => 'CK'],
            ['name' => 'Fiji', 'continent_id' => '4', 'code' => 'FJ'],
            ['name' => 'French Polynesia', 'continent_id' => '4', 'code' => 'PF'],
            ['name' => 'French Southern Territories', 'continent_id' => '4', 'code' => 'TF'],
            ['name' => 'Guam', 'continent_id' => '4', 'code' => 'GU'],
            ['name' => 'Heard Island and McDonald Islands', 'continent_id' => '4', 'code' => 'HM'],
            ['name' => 'Kiribati', 'continent_id' => '4', 'code' => 'KI'],
            ['name' => 'Marshall Islands', 'continent_id' => '4', 'code' => 'MH'],
            ['name' => 'Micronesia', 'continent_id' => '4', 'code' => 'FM'],
            ['name' => 'Nauru', 'continent_id' => '4', 'code' => 'NR'],
            ['name' => 'New Caledonia', 'continent_id' => '4', 'code' => 'NC'],
            ['name' => 'New Zealand', 'continent_id' => '4', 'code' => 'NZ'],
            ['name' => 'Niue', 'continent_id' => '4', 'code' => 'NU'],
            ['name' => 'Norfolk Island', 'continent_id' => '4', 'code' => 'NF'],
            ['name' => 'Northern Mariana Islands', 'continent_id' => '4', 'code' => 'MP'],
            ['name' => 'Palau', 'continent_id' => '4', 'code' => 'PW'],
            ['name' => 'Papua New Guinea', 'continent_id' => '4', 'code' => 'PG'],
            ['name' => 'Pitcairn Islands', 'continent_id' => '4', 'code' => 'PN'],
            ['name' => 'Samoa', 'continent_id' => '4', 'code' => 'WS'],
            ['name' => 'Solomon Islands', 'continent_id' => '4', 'code' => 'SB'],
            ['name' => 'Online English', 'continent_id' => '8', 'code' => 'ON-EN'],
            ['name' => 'Online French', 'continent_id' => '8', 'code' => 'ON-FR'],
            ['name' => 'Online German', 'continent_id' => '8', 'code' => 'ON-DE'],
            ['name' => 'Online Italian', 'continent_id' => '8', 'code' => 'ON-IT'],
            ['name' => 'Online Polish', 'continent_id' => '8', 'code' => 'ON-PL'],
            ['name' => 'Online Portuguese', 'continent_id' => '8', 'code' => 'ON-PT'],
            ['name' => 'Online Spanish', 'continent_id' => '8', 'code' => 'ON-ES'],
        ];

        //dump($countries);
        /*foreach ($countries as $key => $country) {
            DB::table('countries')->insert([
                'id' => $country['id'],
                'name' => $country['name'],
                'continent_id' => $country['continent_id'],
                'code' => $country['code'],
            ]);
        }*/

        collect($countries)->each(function ($country) {
            Country::create($country);
        });
    }
}
