<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*$regions = [
            [
                'id' => '1',
                'country_id' => '1',
                'name' => 'Alabama',
                'languages' => [
                    'nl' => 'Alabama NL',
                ],
                'timezone' => '-6:00'
            ],
        ];*/

        $regions = [
            [
                "id" => 1,
                "country_id" => 2,
                "name" => "Alabama",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 2,
                "country_id" => 2,
                "name" => "Alaska",
                "timezone" => "-9:00",
                "languages" => [],
            ],
            [
                "id" => 3,
                "country_id" => 2,
                "name" => "Arizona",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 4,
                "country_id" => 228,
                "name" => "Western Australia",
                "timezone" => "+08:00",
                "languages" => [],
            ],
            [
                "id" => 5,
                "country_id" => 228,
                "name" => "South Australia",
                "timezone" => "+09:30",
                "languages" => [],
            ],
            [
                "id" => 6,
                "country_id" => 228,
                "name" => "Northern Territory",
                "timezone" => "+09:30",
                "languages" => [],
            ],
            [
                "id" => 7,
                "country_id" => 228,
                "name" => "New South Wales",
                "timezone" => "+10:00",
                "languages" => [],
            ],
            [
                "id" => 8,
                "country_id" => 228,
                "name" => "Tasmania",
                "timezone" => "+10:00",
                "languages" => [],
            ],
            [
                "id" => 9,
                "country_id" => 228,
                "name" => "Victoria",
                "timezone" => "+10:00",
                "languages" => [],
            ],
            [
                "id" => 10,
                "country_id" => 228,
                "name" => "Australian Capital Territory",
                "timezone" => "+10:00",
                "languages" => [],
            ],
            [
                "id" => 11,
                "country_id" => 228,
                "name" => "Queensland",
                "timezone" => "+10:00",
                "languages" => [],
            ],
            [
                "id" => 12,
                "country_id" => 228,
                "name" => "Lord Howe Island",
                "timezone" => "+10:30",
                "languages" => [],
            ],
            [
                "id" => 13,
                "country_id" => 228,
                "name" => "Macquarie Island",
                "timezone" => "+11:00",
                "languages" => [],
            ],
            [
                "id" => 14,
                "country_id" => 2,
                "name" => "Arkansas",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 15,
                "country_id" => 2,
                "name" => "California",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 16,
                "country_id" => 2,
                "name" => "Colorado",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 17,
                "country_id" => 2,
                "name" => "Connecticut",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 18,
                "country_id" => 2,
                "name" => "Delaware",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 19,
                "country_id" => 2,
                "name" => "District of Columbia",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 20,
                "country_id" => 2,
                "name" => "Florida",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 21,
                "country_id" => 2,
                "name" => "Georgia",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 22,
                "country_id" => 2,
                "name" => "Georgia",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 23,
                "country_id" => 2,
                "name" => "Hawaii",
                "timezone" => "-10:00",
                "languages" => [],
            ],
            [
                "id" => 24,
                "country_id" => 2,
                "name" => "Idaho",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 25,
                "country_id" => 2,
                "name" => "Illinois",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 26,
                "country_id" => 2,
                "name" => "Indiana",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 27,
                "country_id" => 2,
                "name" => "Iowa",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 28,
                "country_id" => 2,
                "name" => "Kansas",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 29,
                "country_id" => 2,
                "name" => "Kentucky",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 30,
                "country_id" => 2,
                "name" => "Louisiana",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 31,
                "country_id" => 2,
                "name" => "Maine",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 32,
                "country_id" => 2,
                "name" => "Maryland",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 33,
                "country_id" => 2,
                "name" => "Massachusetts",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 34,
                "country_id" => 2,
                "name" => "Michigan",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 35,
                "country_id" => 2,
                "name" => "Minnesota",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 36,
                "country_id" => 2,
                "name" => "Mississippi",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 37,
                "country_id" => 2,
                "name" => "Missouri",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 38,
                "country_id" => 2,
                "name" => "Montana",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 39,
                "country_id" => 2,
                "name" => "Nebraska",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 40,
                "country_id" => 2,
                "name" => "Nevada",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 41,
                "country_id" => 2,
                "name" => "New Hampshire",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 42,
                "country_id" => 2,
                "name" => "New Jersey",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 43,
                "country_id" => 2,
                "name" => "New Mexico",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 44,
                "country_id" => 2,
                "name" => "New York",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 45,
                "country_id" => 2,
                "name" => "North Carolina",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 46,
                "country_id" => 2,
                "name" => "North Dakota",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 47,
                "country_id" => 2,
                "name" => "Ohio",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 48,
                "country_id" => 2,
                "name" => "Oklahoma",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 49,
                "country_id" => 2,
                "name" => "Oregon",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 50,
                "country_id" => 2,
                "name" => "Pennsylvania",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 51,
                "country_id" => 2,
                "name" => "Rhode Island",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 52,
                "country_id" => 2,
                "name" => "South Carolina",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 53,
                "country_id" => 2,
                "name" => "South Dakota",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 54,
                "country_id" => 2,
                "name" => "Tennessee",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 55,
                "country_id" => 2,
                "name" => "Texas",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 56,
                "country_id" => 2,
                "name" => "Utah",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 57,
                "country_id" => 2,
                "name" => "Vermont",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 58,
                "country_id" => 2,
                "name" => "Virginia",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 59,
                "country_id" => 2,
                "name" => "Washington",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 60,
                "country_id" => 2,
                "name" => "West Virginia",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 61,
                "country_id" => 2,
                "name" => "Wisconsin (WI)",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 62,
                "country_id" => 2,
                "name" => "Wyoming",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 63,
                "country_id" => 1,
                "name" => "Lombardia",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 64,
                "country_id" => 223,
                "name" => "England",
                "timezone" => "Z",
                "languages" => [],
            ],
            [
                "id" => 65,
                "country_id" => 223,
                "name" => "Northern Ireland",
                "timezone" => "Z",
                "languages" => [],
            ],
            [
                "id" => 66,
                "country_id" => 223,
                "name" => "Scotland",
                "timezone" => "Z",
                "languages" => [],
            ],
            [
                "id" => 67,
                "country_id" => 223,
                "name" => "Wales",
                "timezone" => "Z",
                "languages" => [],
            ],
            [
                "id" => 68,
                "country_id" => 1,
                "name" => "Abruzzo",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 69,
                "country_id" => 1,
                "name" => "Basilicata",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 70,
                "country_id" => 1,
                "name" => "Calabria",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 71,
                "country_id" => 1,
                "name" => "Campania",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 72,
                "country_id" => 1,
                "name" => "Emilia-Romagna",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 73,
                "country_id" => 1,
                "name" => "Friuli-Venezia Giulia",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 74,
                "country_id" => 1,
                "name" => "Lazio",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 75,
                "country_id" => 1,
                "name" => "Liguria",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 76,
                "country_id" => 1,
                "name" => "Marche",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 77,
                "country_id" => 1,
                "name" => "Molise",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 78,
                "country_id" => 1,
                "name" => "Piemonte",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 79,
                "country_id" => 1,
                "name" => "Puglia",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 80,
                "country_id" => 1,
                "name" => "Sardegna",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 81,
                "country_id" => 1,
                "name" => "Sicilia",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 82,
                "country_id" => 1,
                "name" => "Toscana",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 83,
                "country_id" => 1,
                "name" => "Trentino-Alto Adige",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 84,
                "country_id" => 1,
                "name" => "Umbria",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 85,
                "country_id" => 1,
                "name" => "Valle d'Aosta",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 86,
                "country_id" => 1,
                "name" => "Veneto",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 87,
                "country_id" => 185,
                "name" => "Auvergne-Rhône-Alpes",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 88,
                "country_id" => 185,
                "name" => "Bourgogne-Franche-Comté",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 89,
                "country_id" => 185,
                "name" => "Bretagne",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 90,
                "country_id" => 185,
                "name" => "Corse",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 91,
                "country_id" => 185,
                "name" => "Centre-Val de Loire",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 92,
                "country_id" => 185,
                "name" => "Grand Est",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 93,
                "country_id" => 185,
                "name" => "Hauts-de-France",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 94,
                "country_id" => 185,
                "name" => "Île-de-France",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 95,
                "country_id" => 185,
                "name" => "Nouvelle-Aquitaine",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 96,
                "country_id" => 185,
                "name" => "Normandy",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 97,
                "country_id" => 185,
                "name" => "Occitanie",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 98,
                "country_id" => 185,
                "name" => "Provence-Alpes-Côte d'Azur",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 99,
                "country_id" => 185,
                "name" => "Pays de la Loire",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 100,
                "country_id" => 186,
                "name" => "Brandenburg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 101,
                "country_id" => 74,
                "name" => "Alberta",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 102,
                "country_id" => 74,
                "name" => "British Columbia",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 103,
                "country_id" => 74,
                "name" => "Manitoba",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 104,
                "country_id" => 74,
                "name" => "New Brunswick",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 105,
                "country_id" => 74,
                "name" => "Newfoundland and Labrador",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 106,
                "country_id" => 74,
                "name" => "Nova Scotia",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 107,
                "country_id" => 74,
                "name" => "Northwest Territories",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 108,
                "country_id" => 74,
                "name" => "Nunavut",
                "timezone" => "-7:00",
                "languages" => [],
            ],
            [
                "id" => 109,
                "country_id" => 74,
                "name" => "Ontario",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 110,
                "country_id" => 74,
                "name" => "Prince Edward Island",
                "timezone" => "-3:00",
                "languages" => [],
            ],
            [
                "id" => 111,
                "country_id" => 74,
                "name" => "Quebec",
                "timezone" => "-5:00",
                "languages" => [],
            ],
            [
                "id" => 112,
                "country_id" => 74,
                "name" => "Saskatchewan",
                "timezone" => "-6:00",
                "languages" => [],
            ],
            [
                "id" => 113,
                "country_id" => 74,
                "name" => "Yukon",
                "timezone" => "-8:00",
                "languages" => [],
            ],
            [
                "id" => 114,
                "country_id" => 134,
                "name" => "Southern",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 115,
                "country_id" => 134,
                "name" => "Haifa",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 116,
                "country_id" => 134,
                "name" => "Jerusalem",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 117,
                "country_id" => 134,
                "name" => "Central",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 118,
                "country_id" => 134,
                "name" => "Tel Aviv",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 119,
                "country_id" => 134,
                "name" => "Northern",
                "timezone" => "+2:00",
                "languages" => [],
            ],
            [
                "id" => 120,
                "country_id" => 185,
                "name" => "Martinique",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 121,
                "country_id" => 185,
                "name" => "Guadeloupe",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 122,
                "country_id" => 185,
                "name" => "La Réunion",
                "timezone" => "+4:00",
                "languages" => [],
            ],
            [
                "id" => 123,
                "country_id" => 185,
                "name" => "Mayotte",
                "timezone" => "+3:00",
                "languages" => [],
            ],
            [
                "id" => 124,
                "country_id" => 185,
                "name" => "Guyane (Française)",
                "timezone" => "-4:00",
                "languages" => [],
            ],
            [
                "id" => 125,
                "country_id" => 186,
                "name" => "Berlin",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 126,
                "country_id" => 186,
                "name" => "Baden-Württemberg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 127,
                "country_id" => 186,
                "name" => "Bayern",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 128,
                "country_id" => 186,
                "name" => "Bremen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 129,
                "country_id" => 186,
                "name" => "Hessen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 130,
                "country_id" => 186,
                "name" => "Hamburg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 131,
                "country_id" => 186,
                "name" => "Mecklenburg-Vorpommern",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 132,
                "country_id" => 186,
                "name" => "Niedersachsen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 133,
                "country_id" => 186,
                "name" => "Nordrhein-Westfalen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 134,
                "country_id" => 186,
                "name" => "Rheinland-Pfalz",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 135,
                "country_id" => 186,
                "name" => "Schleswig-Holstein",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 136,
                "country_id" => 186,
                "name" => "Saarland",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 137,
                "country_id" => 186,
                "name" => "Sachsen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 138,
                "country_id" => 186,
                "name" => "Sachsen-Anhalt",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 139,
                "country_id" => 186,
                "name" => "Thüringen",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 140,
                "country_id" => 217,
                "name" => "Andalusia",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Andalucía",
                    ],
                ],
            ],
            [
                "id" => 141,
                "country_id" => 217,
                "name" => "Catalonia",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Cataluña",
                    ],
                ],
            ],
            [
                "id" => 142,
                "country_id" => 217,
                "name" => "Madrid",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 143,
                "country_id" => 217,
                "name" => "Valencian Community",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Comunidad Valenciana",
                    ],
                ],
            ],
            [
                "id" => 144,
                "country_id" => 217,
                "name" => "Galicia",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 145,
                "country_id" => 217,
                "name" => "Castile and León",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Castilla y León",
                    ],
                ],
            ],
            [
                "id" => 146,
                "country_id" => 217,
                "name" => "Basque Country",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "País Vasco",
                    ],
                ],
            ],
            [
                "id" => 147,
                "country_id" => 217,
                "name" => "Canary Islands",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Canarias",
                    ],
                ],
            ],
            [
                "id" => 148,
                "country_id" => 217,
                "name" => "Castile-La Mancha",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Castilla-La Mancha",
                    ],
                ],
            ],
            [
                "id" => 149,
                "country_id" => 217,
                "name" => "Region of Murcia",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Región de Murcia",
                    ],
                ],
            ],
            [
                "id" => 150,
                "country_id" => 217,
                "name" => "Aragón",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 151,
                "country_id" => 217,
                "name" => "Extremadura",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 152,
                "country_id" => 217,
                "name" => "Balearic Islands",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Islas Baleares",
                    ],
                ],
            ],
            [
                "id" => 153,
                "country_id" => 217,
                "name" => "Asturias",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 154,
                "country_id" => 217,
                "name" => "Navarre",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "es",
                        "name" => "Navarra",
                    ],
                ],
            ],
            [
                "id" => 155,
                "country_id" => 217,
                "name" => "Cantabria",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 156,
                "country_id" => 217,
                "name" => "La Rioja",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 157,
                "country_id" => 217,
                "name" => "Ceuta",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 158,
                "country_id" => 217,
                "name" => "Melilla",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 159,
                "country_id" => 173,
                "name" => "Vienna",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Wien",
                    ],
                ],
            ],
            [
                "id" => 160,
                "country_id" => 173,
                "name" => "Lower Austria",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Niederösterreich",
                    ],
                ],
            ],
            [
                "id" => 161,
                "country_id" => 173,
                "name" => "Upper Austria",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Oberösterreich",
                    ],
                ],
            ],
            [
                "id" => 162,
                "country_id" => 173,
                "name" => "Styria",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Steiermark",
                    ],
                ],
            ],
            [
                "id" => 163,
                "country_id" => 173,
                "name" => "Tyrol",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Tirol",
                    ],
                ],
            ],
            [
                "id" => 164,
                "country_id" => 173,
                "name" => "Carinthia",
                "timezone" => "+1:00",
                "languages" => [
                    [
                        "locale" => "de",
                        "name" => "Kärnten",
                    ],
                ],
            ],
            [
                "id" => 165,
                "country_id" => 173,
                "name" => "Salzburg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 166,
                "country_id" => 173,
                "name" => "Vorarlberg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 167,
                "country_id" => 173,
                "name" => "Burgenland",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 168,
                "country_id" => 220,
                "name" => "Region Basel - Nordwestschweiz",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 169,
                "country_id" => 220,
                "name" => "Region Bern - Mittelland",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 170,
                "country_id" => 220,
                "name" => "Region Zürich / Winterthur",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 171,
                "country_id" => 220,
                "name" => "Region St. Gallen - Ostschweiz",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 172,
                "country_id" => 220,
                "name" => "Zentralschweiz",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 173,
                "country_id" => 220,
                "name" => "Region Biel-Bienne / Neuchâtel - Jura",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 174,
                "country_id" => 220,
                "name" => "Region Genève / Lausanne / Fribourg",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 175,
                "country_id" => 220,
                "name" => "Ticino",
                "timezone" => "+1:00",
                "languages" => [],
            ],
            [
                "id" => 176,
                "country_id" => 220,
                "name" => "Wallis / Valais",
                "timezone" => "+1:00",
                "languages" => [],
            ],
        ];

        collect($regions)->each(function ($region) {
            $languages = $region['languages'];
            unset($region['languages']);
            $created = Region::create($region);
            foreach ($languages as $language => $name){
                $created
                    ->setTranslation('name', $language, $name);
            }
            $created->save();
        });

    }

}


