filter:
    excluded_paths: 
        - "tests/"
        - "public/"
        - "resources/js/vendor/"
        - "database/"
    
    dependency_paths:
        - "vendor/"

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        #fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        #fix_doc_comments: true

build:
    image: default-bionic
    environment:
        php:
            version: 8.1.2
    services:
        mysql: 5.7
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
        coverage: 
            tests:
                before:
                  - command: 'cp .env.example .env'
                  - command: "mysql -e 'create database scrutinizer;'"
                 
                override:
                  - command: './vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                    coverage:
                      file: build/logs/clover.xml   # <- Set this to where we find the coverage data.
                                                  #    The path is relative to the current directory.
                      format: clover
